In [4]:
import numpy as np

print(np)
print(np.__version__)

a = np.arange(15).reshape(3, 5)
print(a)
print(type(a))

print(a.ndim) #陣列有多少維度
print(a.shape) #每個維度的大小
print(a.size) #陣列當中有幾個元素
print(a.dtype) #陣列中的資料型態
print(a.itemsize) #陣列中每個元素佔用的空間
print(a.data) #陣列所存在的記憶體位置

<module 'numpy' from '/Users/apple/opt/anaconda3/lib/python3.8/site-packages/numpy/__init__.py'>
1.19.2
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
<class 'numpy.ndarray'>
2
(3, 5)
15
int64
8
