# 範例
***

# [教學目標]

* 正確的使用 NumPy 中的算術運算
* 了解 NumPy 陣列與數學矩陣的關係
* 知道 NumPy 與 SciPy 差異為何


In [1]:
# 載入 NumPy 套件
import numpy as np

# 檢查正確載入與版本
print(np)
print(np.__version__)

<module 'numpy' from '/Users/wei/.virtualenvs/py3/lib/python3.6/site-packages/numpy/__init__.py'>
1.16.1


In [ ]:
# 運算的時候，陣列的形狀 (shape) 必須相同，或是遵循廣播 (broadcasting) 規則，才能正確進行 element-wise 運算。規則如下：
## 1. 兩個陣列形狀完全相同
## 2. 比較兩個陣列的維度，如果維度的形狀相同的話，可以進行廣播
## 3. 比較兩個陣列的維度，其中一個維度為1的話，可以進行廣播


In [2]:
# 相同大小的陣列運算

import numpy as np

a = np.array( [20,30,40,50] )
b = np.arange( 4 )

print(a + b)
print(a * b)

[20 31 42 53]
[  0  30  80 150]


In [3]:
# 常數與陣列運算
# 常術與陣列運算會符合「廣播（Broadcast）」運算的特性，廣播特並會將常數補齊成多維的陣列。

import numpy as np

a = np.array( [20,30,40,50] )

print(a - 2)
print(a / 10)


[18 28 38 48]
[2. 3. 4. 5.]


In [4]:
# 不同大小的陣列運算
# 不同大小的陣列運算也會符合「廣播」運算的特性：

import numpy as np

data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])

print(data + ones_row)


[[2 3]
 [4 5]
 [6 7]]


In [5]:
# 陣列運算與容器運算的差異
# 陣列有「對齊」跟「廣播」兩種重要的運算特性，這個其實就是我們講的向量運算特性。
# 換句話說，在向量的運算中，是以「整組」為單位在進行運算，這是和 Python 容器最大的差異之一。

a = np.array( [20,30,40,50] )
print(a + 1)

a = [20, 30, 40, 50]
b = []
for i in a:
    b.append(i+1)
print(b)


[21 31 41 51]
[21, 31, 41, 51]


In [6]:
# 用於陣列的矩陣運算

a = np.array([[1.0, 2.0], [3.0, 4.0]])
print(a)
y = np.array([[5.], [7.]])
print(y)

[[1. 2.]
 [3. 4.]]
[[5.]
 [7.]]


In [7]:
print(a.transpose())
print(np.linalg.inv(a))
print(np.trace(a))
print(np.linalg.solve(a, y))


[[1. 3.]
 [2. 4.]]
[[-2.   1. ]
 [ 1.5 -0.5]]
5.0
[[-3.]
 [ 4.]]
