In [2]:
import numpy as np
print(np) # <module 'numpy' from '.../numpy/__init__.py'>
print(np.__version__) # 1.20.1

<module 'numpy' from '/Users/apple/opt/anaconda3/lib/python3.8/site-packages/numpy/__init__.py'>
1.19.2


In [5]:
# 建立 NumPy array (陣列)
# 要用序列數字產生等差一維陣列的話，可以使用 arange() 與 linspace() 函式，兩者的函式引數很類似，
# 其中結束值為必填，起始值、間隔值非必填。產生的序列數字包含起始值但不包含結束值，也就是 [start, stop) 的表示方式。

# 1. range: 只能生成整型的序列
# 2. np.arange([start,] stop[, step]): 
#    可生成整型、浮點型序列
#    當使用非整數步驟(如0.1)時，結果往往不一致。對於這些情況，最好使用‘linspace’
# 3. linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
#
# Python 內建的列表（List）是由獨立的元素所組成的容器，元素的型態可以不同。
# 而 NumPy 陣列是同質性的（homogeneous）的物件，也就是每個元素的型態都必須相同。因此在底層定義與操作略有差異。
# 陣列的元素會配置在連續的記憶體位置，而列表則沒有這樣的限制。

# NdArray
# 建立 3x5 的陣列，並且利用 type() 查看其類型。
a = np.arange(15).reshape(3, 5)
print(a)
# array([[ 0,  1,  2,  3,  4],
#        [ 5,  6,  7,  8,  9],
#        [10, 11, 12, 13, 14]])

print(type(a)) # <type 'numpy.ndarray'>
print(a.ndim)  # 陣列有多少維度 2
print(a.shape) # 每個維度的大小 (3, 5)
print(a.size)  # 陣列當中有幾個元素 15
print(a.dtype) # 陣列中的資料型態 int64
print(a.itemsize) # 陣列中每個元素佔用的空間 8
print(a.data) # 陣列所存在的記憶體位置
print(a.strides)
print(a.flags)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
<class 'numpy.ndarray'>
2
(3, 5)
15
int64
8


In [7]:
# List 與 Array 的轉換 
# list(a) 只會把第一層的元素轉換成 List，多層的話只有第一層會轉；
# tolist() 才能達成多層的型態轉換。
list(a)
print(list(a))
# [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]

a.tolist()
print(a.tolist())
# [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]
[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]
