# 範例
***

# [教學目標]

* 認識 NumPy 中提供的資料型態
* 了解各種型態的差異與定義
* 正確的比較型態判斷



In [4]:
# 載入 NumPy 套件
import numpy as np

# 檢查正確載入與版本
print(np)
print(np.__version__)

<module 'numpy' from '/Users/apple/opt/anaconda3/lib/python3.8/site-packages/numpy/__init__.py'>
1.19.2


In [5]:
# 從一個陣列開始

a = np.arange(15).reshape(3, 5)
print(a) # 利用 print(...) 印出陣列
a # 利用 Jupyter 印出陣列

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
# 陣列的常用屬性

print(a.dtype) # int64
print(a.itemsize) # 8


int64
8


In [7]:
# numpy 中的型態判斷
# NumPy 型態的定義是一個 np.dtype 的物件，包含「型態名稱」、「表示範圍」及「儲存空間」等等的資訊。
# 而「is」跟「==」的差異在於 is 是強比較，必須要所有規格都相同，包含是哪一種物件；
# 而 == 的比較只會考慮自定義的規則，例如只需要物件的表現形式

print(a.dtype == 'int64') 
#print(a.dtype is 'int64') 
print(a.dtype is np.int64) 


True
False


In [8]:
# 資料型態的正確用法

print(a.dtype == 'int64') # True
print(a.dtype == np.int64) # True
print(a.dtype is np.dtype('int64')) # True


True
True
True


In [9]:
print(a.dtype == 'int') 
print(a.dtype == np.int) 
print(a.dtype == np.dtype('int')) 

# int 代表「執行電腦中最大可表示的範圍」，會取決於電腦不同而產生不同的結果

True
True
True
